name: Deploy to FTP Server

on:
  push:
    branches: main

jobs:
  deploy:
    name: 🚀 Deploy website every commit
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v4

      - name: 🚚 Use node js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x


      - name: 📂 Build website
        run: |
          npm install
          npm run build
        uses: ./

      - name: 🚀 Deploy to FTP Server
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: ${{ GIT_FTP_SERVER }}
          username: ${{ GIT_FTP_USERNAME }}
          password: ${{ GIT_FTP_PASSWORD }}
          protocol: 'ftps'
          local-dir: './build'
          remote-dir: '/'
          sync-options: '--delete --verbose'
