name: Deploy to FTP Server

on:
  push:
    branches: main

jobs:
  deploy:
    name: 🚀 Deploy website every commit
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v4

      - name: 🚚 Use node js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'



      - name: 📂 Build website
        run: |
          npm install
          npm run build

      - name: 🚀 Deploy to FTP Server
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: ${{ secrets.GIT_FTP_SERVER }}
          username: ${{ secrets.GIT_FTP_USERNAME }}
          password: ${{ secrets.GIT_FTP_PASSWORD }}
          protocol: 'ftps'
          local-dir: './dist'
          server-dir: /pms.seftcons.com/
    
