name: Deploy to FTP Server

on:
  push:
    branches: [master]

jobs:
  deploy:
    name: 🚀 Deploy website every commit
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v4

      - name: 📂 Sync files
        run:   npm install && npm run build
        uses: ./
        with:
          server: ${{ secrets.git_ftp_server }}
          username: ${{ secrets.ftp_username }}
          password: ${{ secrets.ftp_password }}
          local-dir: './build'
          remote-dir: '/'
          sync-options: '--delete --verbose'
